import { useMemo, useState } from 'react';
import {
  Activity, Bot, Camera, Check, ChevronDown, CircleAlert, Cpu, Database,
  Gauge, Lightbulb, MapPin, MoreHorizontal, Plus, RefreshCw, Search,
  Settings2, ShieldCheck, Sparkles, Video, Wifi, Zap
} from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import Sidebar from './Sidebar';
import Header from './Header';
import '../Style/AnalyticsScreen.css';

const trend = [
  { day: 'Mon', visits: 760, sales: 64, accuracy: 87 }, { day: 'Tue', visits: 1120, sales: 79, accuracy: 91 },
  { day: 'Wed', visits: 1290, sales: 105, accuracy: 89 }, { day: 'Thu', visits: 1370, sales: 98, accuracy: 93 },
  { day: 'Fri', visits: 1660, sales: 132, accuracy: 94 }, { day: 'Sat', visits: 1490, sales: 118, accuracy: 91 },
  { day: 'Sun', visits: 1570, sales: 146, accuracy: 95 }
];

const cameras = [
  ['CAM-01', 'Entrance', 'Online'], ['CAM-02', 'Main Floor - North', 'Online'], ['CAM-03', 'Main Floor - South', 'Online'], ['CAM-04', 'Billing Counter 1', 'Online'],
  ['CAM-05', 'Fitting Room', 'Online'], ['CAM-06', 'Accessories Section', 'Online'], ['CAM-07', 'Stock Room', 'Offline'], ['CAM-08', 'Parking / Outside', 'Online']
];

const IconBox = ({ icon: Icon, color = 'blue' }) => <span className={`an-icon ${color}`}><Icon size={18} /></span>;
const Chip = ({ children, tone = 'green' }) => <span className={`an-chip ${tone}`}><i />{children}</span>;
const Toggle = ({ enabled = true }) => { const [on, setOn] = useState(enabled); return <button aria-label="Toggle setting" onClick={() => setOn(!on)} className={`an-toggle ${on ? 'on' : ''}`}><span /></button>; };
const Button = ({ children, outline = false, icon: Icon = null }) => <button className={`an-button ${outline ? 'outline' : ''}`}>{Icon && <Icon size={15} />}{children}</button>;
const Card = ({ title, subtitle, action, children, className = '' }) => <section className={`an-card ${className}`}><div className="an-card-head"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>{children}</section>;

function Stat({ label, value, note, icon: Icon, color = 'blue' }) {
  return <div className="an-stat"><div><p>{label}</p><strong>{value}</strong><small className={note.includes('↓') ? 'red' : ''}>{note}</small></div><IconBox icon={Icon} color={color} /><div className="an-spark">{[13, 20, 16, 26, 21, 34, 26, 39].map((h, index) => <b key={index} style={{ height: h }} />)}</div></div>;
}

function CameraManagement() {
  return <Screen title="Camera Management" subtitle="Monitor, configure and maintain your camera network" action={<Button icon={Plus}>Add Camera</Button>}>
    <div className="an-stats"><Stat label="Total Cameras" value="12" note="↑ 20% vs last month" icon={Camera} /><Stat label="Online" value="10" note="↑ 8% vs last month" icon={Wifi} color="green" /><Stat label="Offline" value="2" note="↓ 50% vs last month" icon={CircleAlert} color="red" /><Stat label="Avg. Uptime (30d)" value="98.4%" note="↑ 2.1% vs last month" icon={Activity} /></div>
    <Card title="Camera Fleet" subtitle="Live view of all cameras across your store network" action={<Button outline>All Zones <ChevronDown size={14} /></Button>}>
      <div className="an-camera-grid">{cameras.map(([id, zone, status], index) => <article className="an-camera" key={id}><div className={`an-camera-preview preview-${index % 4}`}><span className="an-live"><i /> LIVE</span><button><MoreHorizontal size={17} /></button></div><div className="an-camera-info"><Chip tone={status === 'Online' ? 'green' : 'red'}>{status}</Chip><strong>{id}</strong><span>{zone}</span><small>1920 x 1080 &nbsp; 30 FPS</small></div></article>)}</div>
    </Card>
    <Card title="Camera Health Table" subtitle="Network status and storage allocation"><div className="an-table-wrap"><table className="an-table"><thead><tr><th>Camera ID</th><th>Zone / Location</th><th>IP Address</th><th>Status</th><th>Uptime (30d)</th><th>Last Ping</th><th>Storage Used</th><th>Actions</th></tr></thead><tbody>{cameras.map(([id, zone, status], i) => <tr key={id}><td><b>{id}</b></td><td>{zone}</td><td>192.168.1.{101 + i}</td><td><Chip tone={status === 'Online' ? 'green' : 'red'}>{status}</Chip></td><td>{status === 'Online' ? `${98 + (i % 2)}.${i}%` : '72.3%'}</td><td>{i === 6 ? '12 min ago' : `${i + 1} min ago`}</td><td><span className="an-mini-progress"><i style={{ width: `${35 + i * 6}%` }} /></span> {280 + i * 32} GB</td><td><button className="an-icon-button"><Settings2 size={15} /></button></td></tr>)}</tbody></table></div></Card>
    <div className="an-two"><Card title="Network Bandwidth Usage" subtitle="All cameras" action={<Button outline>Last 24 Hours <ChevronDown size={13} /></Button>}><div className="an-chart"><ResponsiveContainer><AreaChart data={trend}><defs><linearGradient id="camFill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#4f46e5" stopOpacity=".34"/><stop offset="1" stopColor="#4f46e5" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0f7"/><XAxis dataKey="day" tickLine={false} axisLine={false}/><YAxis hide/><Tooltip/><Area dataKey="visits" stroke="#4f46e5" strokeWidth={2} fill="url(#camFill)" /></AreaChart></ResponsiveContainer></div></Card><Card title="Storage & Retention" subtitle="Footage storage allocation"><div className="an-storage"><div className="an-ring"><span>62%<small>of 1 TB used</small></span></div><div><p><i className="an-dot blue" />Used Space <b>620 GB (62%)</b></p><p><i className="an-dot green" />Free Space <b>380 GB (38%)</b></p><label>Retention Policy<select><option>Keep footage for 30 days</option></select></label></div></div></Card></div>
    <div className="an-two"><Card title="Firmware & Software Updates" subtitle="Updates available for 2 cameras" action={<Button outline>Update All</Button>}><div className="an-simple-list">{['CAM-03   v2.0.8     Update Available', 'CAM-07   v2.0.8     Update Available', 'CAM-01   v2.1.0     Up to date'].map((row, i) => <div key={row}><span>{row}</span>{i < 2 ? <Button outline>Update</Button> : <Chip>Up to date</Chip>}</div>)}</div></Card><Card title="Maintenance Schedule" subtitle="Upcoming maintenance and warranty information" action={<Button outline icon={Plus}>Add Schedule</Button>}><div className="an-simple-list">{['25 May 2025   CAM-02   Lens Cleaning', '28 May 2025   CAM-04   Hardware Check', '05 Jun 2025   CAM-03   Firmware Update'].map((row, i) => <div key={row}><span>{row}</span><Chip tone={i === 2 ? 'orange' : 'blue'}>{i === 2 ? 'Pending' : 'Scheduled'}</Chip></div>)}</div></Card></div>
  </Screen>;
}

function AiConfiguration() {
  const models = [['SCRFD-500MF Face Detection', 'v2.1', 'Face Detection', '97.2%', 'Active'], ['YOLOv11 People Detection', 'v1.3', 'Person Detection', '96.5%', 'Active'], ['ArcFace MobileFaceNet Recognition', 'v2.2', 'Face Recognition', '96.8%', 'Active'], ['YOLOv8 Object Detection (General)', 'v1.0', 'Object Detection', '94.1%', 'Testing']];
  const features = [['Face Recognition', 'Identify known individuals'], ['Anti-Spoofing / Liveness', 'Prevent fake face detection'], ['Crowd Density Detection', 'Monitor crowd levels in real-time'], ['Loitering Detection', 'Detect unusual loitering behavior'], ['Uniform Compliance', 'Check employee uniform using AI'], ['Heatmap Generation', 'Generate footfall and movement heatmaps']];
  return <Screen title="AI Configuration" subtitle="Manage detection models, thresholds and AI behavior" action={<Button icon={Plus}>Add Model</Button>}>
    <div className="an-stats"><Stat label="Active Models" value="4" note="↑ 33% vs last month" icon={Cpu} /><Stat label="Avg. Detection Accuracy" value="96.8%" note="↑ 1.2% vs last month" icon={Gauge} color="green" /><Stat label="Inference Speed" value="28 FPS" note="↑ 12% vs last month" icon={Zap} /><Stat label="Last Model Update" value="3 days ago" note="● Model performing well" icon={Activity} /></div>
    <Card title="Deployed AI Models" subtitle="Currently active models in production" action={<Button outline icon={Plus}>Deploy New Model</Button>}><div className="an-table-wrap"><table className="an-table"><thead><tr><th>Model Name</th><th>Version</th><th>Task Type</th><th>Accuracy</th><th>Status</th><th>Actions</th></tr></thead><tbody>{models.map(row => <tr key={row[0]}><td><b>{row[0]}</b></td><td>{row[1]}</td><td>{row[2]}</td><td className={row[3] === '94.1%' ? 'orange-text' : 'green-text'}><b>{row[3]}</b></td><td><Chip tone={row[4] === 'Active' ? 'green' : 'orange'}>{row[4]}</Chip></td><td className="an-actions"><Button outline>Configure</Button><Button outline>Retrain</Button><Button outline>Rollback</Button></td></tr>)}</tbody></table></div></Card>
    <div className="an-two"><Card title="Detection Thresholds" subtitle="Configure confidence and behavior thresholds"><div className="an-sliders">{[['Confidence Threshold (Object Detection)', '75%'], ['Face Recognition Match Threshold', '0.85'], ['Loitering Time Threshold', '5 min'], ['Crowd Density Threshold', '80%']].map(([label, value], i) => <label key={label}>{label}<input type="range" min="0" max="100" defaultValue={[75, 85, 45, 80][i]} /><b>{value}</b></label>)}</div></Card><Card title="Feature Toggles" subtitle="Enable or disable AI features"><div className="an-feature-list">{features.map(([name, detail]) => <div key={name}><IconBox icon={Bot} /><span><b>{name}</b><small>{detail}</small></span><Toggle /></div>)}</div></Card></div>
    <Card title="Model Performance Trend" subtitle="Accuracy and false positive rate over last 30 days" action={<Button outline>Last 30 Days <ChevronDown size={13}/></Button>}><div className="an-chart large"><ResponsiveContainer><AreaChart data={trend}><CartesianGrid vertical={false} stroke="#edf0f7"/><XAxis dataKey="day" tickLine={false} axisLine={false}/><YAxis domain={[0, 100]} tickFormatter={v => `${v}%`} tickLine={false} axisLine={false}/><Tooltip/><Area dataKey="accuracy" stroke="#4f46e5" fill="#4f46e520" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Card>
    <div className="an-two"><Card title="Training Data & Retraining Pipeline" subtitle="Manage dataset and model retraining" action={<Button icon={RefreshCw}>Retrain Model</Button>}><div className="an-kpis"><div><IconBox icon={Database}/><b>1,240</b><small>New samples collected</small></div><div><IconBox icon={Activity} color="orange"/><b>320</b><small>Annotation queue</small></div><div><IconBox icon={Check} color="green"/><b>18 May 2025</b><small>Last retrained</small></div></div></Card><Card title="A/B Model Testing" subtitle="Compare model performance before deployment" action={<Button outline>View Test Results</Button>}><div className="an-simple-list"><div><span>Accuracy<br/><b>96.2% to 97.1%</b></span><strong className="green-text">↑ 0.9%</strong></div><div><span>Inference Speed<br/><b>28 FPS to 32 FPS</b></span><strong className="green-text">↑ 14%</strong></div><Button>Promote to Production</Button></div></Card></div>
  </Screen>;
}

function RetailIntelligence() {
  const funnel = [['Store Visitors', '100%', '12,460'], ['Product Engagement', '62%', '7,725'], ['Fitting Room Visits', '38%', '4,735'], ['Add to Cart', '28%', '3,487'], ['Purchases', '24%', '2,990']];
  return <Screen title="Retail Intelligence" subtitle="AI-powered insights connecting footfall, behavior and sales">
    <div className="an-stats"><Stat label="Footfall-to-Sales Conversion" value="24%" note="↑ 3% vs last week" icon={UsersIcon} /><Stat label="Avg. Basket Value" value="₹973" note="↑ 7% vs last week" icon={Gauge} color="purple" /><Stat label="Customer Retention Rate" value="41%" note="↑ 5% vs last month" icon={Activity} /><Stat label="Store Efficiency Score" value="88 / 100" note="↑ 6 points vs last month" icon={Sparkles} color="orange" /></div>
    <section className="an-insight"><IconBox icon={Sparkles} color="purple"/><div><h2>AI Executive Summary</h2><p>This week, footfall grew by 12% while conversion held steady at 24%. Fitting Room dwell time increased by 18%, correlating with a 5% rise in average basket value.</p></div><Button icon={RefreshCw}>Regenerate Insight</Button></section>
    <div className="an-two"><Card title="Footfall vs Sales Correlation" subtitle="Visitor trends and revenue movement"><div className="an-chart"><ResponsiveContainer><AreaChart data={trend}><CartesianGrid vertical={false} stroke="#edf0f7"/><XAxis dataKey="day" tickLine={false} axisLine={false}/><YAxis hide/><Tooltip/><Area dataKey="visits" stroke="#2563eb" fill="#2563eb1e" strokeWidth={2}/><Area dataKey="sales" stroke="#7c3aed" fill="#7c3aed12" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Card><Card title="Conversion Funnel Trend" subtitle="From store visitor to purchase"><div className="an-funnel">{funnel.map(([label, value, total], i) => <div key={label}><span>{label}</span><b style={{ width: `${100 - i * 13}%` }}>{value}</b><strong>{total}</strong></div>)}</div></Card></div>
    <div className="an-two"><Card title="Zone Profitability" subtitle="Revenue per square foot (₹)" action={<Button outline>Revenue per Sq. Ft. <ChevronDown size={13}/></Button>}><div className="an-chart"><ResponsiveContainer><BarChart data={[{name:'Entrance', value:1240},{name:'Main Floor',value:1890},{name:'Fitting Room',value:2340},{name:'Billing',value:3120},{name:'Accessories',value:1080}]}><XAxis dataKey="name" tick={{fontSize:10}} tickLine={false} axisLine={false}/><YAxis hide/><Tooltip/><Bar dataKey="value" fill="#4f46e5" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card title="Customer Behavior Segments" subtitle="Based on AI analysis of in-store behavior" action={<a className="an-link">View Details</a>}><div className="an-segments">{[['Browsers','42%','₹420'],['Quick Shoppers','28%','₹890'],['High-Intent','18%','₹2,340'],['Window Shoppers','12%','₹310']].map((x,i)=><div key={x[0]}><IconBox icon={i === 1 ? Zap : UsersIcon} color={['blue','green','purple','orange'][i]}/><b>{x[0]}</b><strong>{x[1]}</strong><small>Avg. Spend: {x[2]}</small></div>)}</div></Card></div>
    <Card title="Predictive Demand & Staffing Recommendation" subtitle="Predicted footfall (Next 7 Days)"><div className="an-recommend"><div className="an-chart"><ResponsiveContainer><BarChart data={trend}><XAxis dataKey="day" tickLine={false} axisLine={false}/><YAxis hide/><Tooltip/><Bar dataKey="visits" fill="#4f46e5" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div><div><IconBox icon={Lightbulb}/><h3>Increase billing staff by 1 on Saturday (2 PM - 6 PM)</h3><p>Based on predicted 18% footfall surge compared to last week. This will help reduce queue time and improve conversion.</p><Button icon={Check}>Apply Recommendation</Button></div></div></Card>
    <div className="an-two"><Card title="Marketing Campaign Impact" subtitle="Performance before and during campaign"><div className="an-chart"><ResponsiveContainer><BarChart data={[{name:'Before Campaign', footfall:840, sales:620},{name:'During Campaign',footfall:1180,sales:910}]}><XAxis dataKey="name" tick={{fontSize:10}} tickLine={false} axisLine={false}/><YAxis hide/><Tooltip/><Bar dataKey="footfall" fill="#3730a3" radius={[3,3,0,0]}/><Bar dataKey="sales" fill="#c4b5fd" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card title="Competitive Benchmark" subtitle="Comparison against chain average"><div className="an-simple-list">{['Footfall (Daily)     1,780 vs 1,420', 'Conversion Rate      24% vs 19%', 'Avg. Basket Value    ₹973 vs ₹820', 'Customer Retention   41% vs 36%'].map(row => <div key={row}><span>{row}</span><strong className="green-text">↑</strong></div>)}</div></Card></div>
  </Screen>;
}

function UsersIcon(props) { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" {...props}><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>; }
function Screen({ title, subtitle, action, children }) { return <div className="dashboard-container"><Sidebar /><div className="main-content-wrapper"><Header title={title} subtitle={subtitle} /><main className="an-scroll"><div className="an-page-bar"><div className="an-search"><Search size={15}/><span>Search {title.toLowerCase()}...</span></div><div className="an-page-actions"><Button outline>Store 1 - Fashion Store <ChevronDown size={13}/></Button>{action}</div></div>{children}</main></div></div>; }

function GeneralWorkspace({ type }) {
  const config = {
    reports: ['Reports', 'Generate and download business insights', 'Report Templates', ['Daily Sales Summary', 'Weekly Footfall Report', 'Monthly Attendance Report', 'Security Incident Log']],
    employees: ['Employees', 'Track attendance, performance and compliance', 'Employee Directory', ['Rahul Kumar - Sales Associate', 'Priya Sharma - Cashier', 'Amit Mehta - Store Manager', 'Sneha Nair - Sales Associate']],
    settings: ['Settings', 'Manage account, team and system preferences', 'Profile & Preferences', ['Profile and account details', 'Team & Roles', 'Notification Preferences', 'Billing & Plan']]
  }[type];
  const [title, subtitle, panel, rows] = config;
  return <Screen title={title} subtitle={subtitle} action={<Button icon={Plus}>{type === 'reports' ? 'New Report' : type === 'employees' ? 'Add Employee' : 'Save Changes'}</Button>}>
    <div className="an-stats">{['This Month', 'Active Today', 'In Progress', 'Performance'].map((label, i) => <Stat key={label} label={label} value={type === 'reports' ? ['34', '6', '9:00 AM', '42%'][i] : type === 'employees' ? ['24', '22', '2', '92%'][i] : ['5', '4', '3', '96%'][i]} note="↑ 12% vs last month" icon={[Activity, UsersIcon, ShieldCheck, Sparkles][i]} color={i === 1 ? 'green' : 'blue'} />)}</div>
    <Card title={panel} subtitle="Manage your current store configuration" action={<Button outline>View All</Button>}><div className="an-simple-list">{rows.map((row, i) => <div key={row}><span><b>{row}</b><br/><small>{type === 'reports' ? 'Ready to generate and download' : 'Enabled for this store account'}</small></span>{type === 'settings' ? <Toggle enabled={i !== 3} /> : <Chip tone={i === 3 ? 'orange' : 'green'}>{type === 'reports' ? 'Ready' : 'Active'}</Chip>}</div>)}</div></Card>
    <div className="an-two"><Card title={type === 'employees' ? 'Attendance Trend' : 'Activity Trend'} subtitle="Current store overview"><div className="an-chart"><ResponsiveContainer><BarChart data={trend}><XAxis dataKey="day" tickLine={false} axisLine={false}/><YAxis hide/><Tooltip/><Bar dataKey="visits" fill="#4f46e5" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card title="Notification Preferences" subtitle="Manage your active configuration"><div className="an-feature-list">{['Email notifications', 'Weekly digest', 'Real-time alerts', 'Security checks'].map((name, i) => <div key={name}><IconBox icon={i === 3 ? ShieldCheck : Activity}/><span><b>{name}</b><small>Enabled for this account</small></span><Toggle enabled={i !== 2}/></div>)}</div></Card></div>
  </Screen>;
}

export default function AnalyticsScreen({ type }) { return useMemo(() => type === 'camera' ? <CameraManagement /> : type === 'ai' ? <AiConfiguration /> : type === 'intelligence' ? <RetailIntelligence /> : <GeneralWorkspace type={type} />, [type]); }
